### ISSUE TITLE
Gitalk在private repo中不工作的解决方案

### ISSUE THREAD

**Issue by Kai5174** [qiubaiying/qiubaiying.github.io#175]
首先感谢一波BY大佬的分享 XDDD， 

回到正题，如果想把自己的仓库设置成私有，且不影响gitalk的评论。 （如果你按照README的设定会发现在gitalk上面有个404，而且不能评论）

解决方案： 新建一个公共仓库，然后在`_config.yml`里面做如下改动

```
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                    #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: qiubaiying.github.io    #仓库名称  <-- 将此行改为新建的仓库名称
  owner: qiubaiying    #github用户名
  admin: qiubaiying
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
```

之后评论就会都放在你新建的公共仓库的issue之下。
